# Generated by Django 2.2.4 on 2019-08-21 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('published_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
